#!/bin/bash -e

# Switch to this script's directory
cd "${0%/*}"

export AUTOSSH_FIRST_POLL=60
export AUTOSSH_POLL=300

# kill all the children when done
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

# is this a registered vessel?
infopath="boats/$(hostname -f)"
if [[ ! -f "${infopath}" ]]
then
  echo "Not a registered machine."
  exit 1
fi

my_port=`cat "${infopath}" | head -n1`

for lighthouse in $(ls lighthouses/*)
do
  ip=$(cat "${lighthouse}" | head -n1)
  autossh -NTR \*:${my_port}:localhost:22 -oStrictHostKeyChecking=accept-new -oExitOnForwardFailure=yes stagecast@${ip} &
done

wait
