#!/bin/bash -e

# Switch to this script's directory
cd "${0%/*}"

export AUTOSSH_POLL=60

# kill all the children when done
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

# is this a registered vessel?
infopath="boats/$(hostname -f)"
if [[ ! -f "${infopath}" ]]
then
  echo "Not a registered machine."
  exit 1
fi

for lighthouse in $(ls lighthouses/*)
do
  ip=$(cat "${lighthouse}" | head -n1)
  ports=(`cat "${infopath}" | head -n1`)

  for iface in eno2 usb0
  do
    while true; do
      # Get the ip:iface mapping for binding
      iface_inets="$(ip addr | awk '/^[0-9]+:/ {
          sub(/:/,"",$2); iface=$2 }
        /^[[:space:]]*inet / {
          split($2, a, "/")
          print a[1], iface
        }')"
      inet=$(echo "${iface_inets}" | grep ${iface} | cut -f1 -d' ')

      if [[ ! -z ${inet} ]]; then
        autossh -NTR \*:${ports[0]}:localhost:22 -oStrictHostKeyChecking=accept-new -oExitOnForwardFailure=yes -oBatchMode=yes -b ${inet} stagecast@${ip} || true
      else
        echo "Cannot bind to interface ${iface}. Retrying in 1 minute."
      fi

      sleep ${AUTOSSH_POLL} # try to reconnect even if the underlying ssh command failed
    done &

    ports=("${ports[@]:1}")
  done
done

wait
