#!/bin/bash -e

# Switch to this script's directory
cd "${0%/*}"

# fix sshd_config
if ! sudo grep -Fxq "GatewayPorts yes" "/etc/ssh/sshd_config"
then
  echo "GatewayPorts yes" | sudo tee -a "/etc/ssh/sshd_config"
  sudo systemctl reload sshd.service
fi

# is this lighthouse registered?
hostname=`hostname -f`
if [[ ! -f "lighthouses/${hostname}" ]]
then
  echo "Hostname wasn't found in the list: ${hostname}."
  exit 1
fi

sudo -i -u stagecast bash <<EOF
authorized_keys=`echo ~/.ssh/authorized_keys`
if [[ ! -f "${authorized_keys}" ]]
then
  mkdir -p ~/.ssh
  touch "${authorized_keys}"
fi

# add new ssh keys
for boat in $(ls boats/*)
do
  boat_name=`basename ${boat}`
  public_key=`cat ${boat} | tail -n1`

  if ! grep -q "${public_key}" "${authorized_keys}"
  then
    echo "${public_key}" >>${authorized_keys}
  fi
done
EOF
