#!/bin/bash -e

cd "${0%/*}"

RT_TABLES="/etc/iproute2/rt_tables"

if ! grep -q $'101\teno2' "${RT_TABLES}"
then
  echo $'101\teno2' | sudo tee -a "${RT_TABLES}"
fi

if ! grep -q $'102\tusb0' "${RT_TABLES}"
then
  echo $'102\tusb0' | sudo tee -a "${RT_TABLES}"
fi

# create the dispaching script
sudo cp source_route /etc/networkd-dispatcher/routable.d/50-source-route
sudo chmod +x /etc/networkd-dispatcher/routable.d/50-source-route
